disabled = false
locale = "zh-CN"
label = "简体中文"
weight = 1
title = "KAI 的个人blog"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "记录KAI的经验笔记，项目复盘和一些碎碎念~"
  logo = "img/kai-logo.svg"

[params.author]
  name = "KAI"
  image = "img/kai-avatar.svg"
  imageQuality = 96
  headline = "记录经验笔记，项目复盘和一些碎碎念~"
  bio = "技术经验、学习笔记、生活记录与思考。"

